version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8881:80"
    volumes:
      - ./app:/var/www/html
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"

#netsh interface portproxy add v4tov4 listenport=8880
#listenaddress=0.0.0.0 connectport=80
#connectaddress=$($(wsl hostname -I).Trim());
# =>
# broke http://localhost:8880/test.php