version: '3'
services:
  app:
    image: phpstorm/php-56-apache-xdebug-25
    ports:
      - "8880:80"
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1 remote_connect_back=1"
#      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1 "
      PHP_IDE_CONFIG: "serverName=localhost"
